# Generated by Django 6.0.1 on 2026-03-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0002_messmenu_outpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
