# Generated by Django 6.0.1 on 2026-03-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0003_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics & Comm'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('IT', 'Information Technology')], max_length=100, null=True, verbose_name='Department (CSE, ECE, MECH, CIVIL, IT)'),
        ),
    ]
